"""v10 P5 — Shadow A/B CLI: ``python -m rl.cli.shadow``."""

from __future__ import annotations

import argparse
import json
import shlex
import sqlite3
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EXIT_OK = 0
EXIT_ERROR = 1


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="rl.cli.shadow")
    p.add_argument("--proposal", type=Path, required=True)
    p.add_argument("--soak-args", type=str, default="")
    p.add_argument("--shadow-db", type=Path, default=Path("rl_shadow.db"))
    p.add_argument("--reports-dir", type=Path, default=ROOT / "reports")
    p.add_argument("--dry-run", action="store_true")
    return p


def build_soak_command(
    proposal: Path, shadow_db: Path, soak_args: str,
) -> list[str]:
    """Compose soak_driver argv. Tier (1/2/3) is inferred by
    soak_driver from `--total-seconds` passed through `--soak-args`."""
    extra = shlex.split(soak_args) if soak_args else []
    return [
        sys.executable, str(ROOT / "tools" / "soak_driver.py"),
        "--cli-pool-size", "2",
        "--shadow-recorder", str(shadow_db),
        "--shadow-proposal", str(proposal),
        *extra,
    ]


def _summarise_shadow_db(shadow_db: Path, soak_run_id: str) -> dict:
    empty = {"n": 0, "agreement_rate": 0.0, "fr_og_7_violations": 0,
             "cand_prod_agreement": 0.0, "candidate_reward": 0.0,
             "production_reward": 0.0, "n_with_ground_truth": 0}
    if not shadow_db.exists():
        return empty
    uri = f"file:/{shadow_db.resolve().as_posix().lstrip('/')}?mode=ro"
    conn = sqlite3.connect(uri, uri=True)
    conn.row_factory = sqlite3.Row
    try:
        rows = conn.execute(
            "SELECT * FROM shadow_episodes WHERE soak_run_id = ?",
            (soak_run_id,),
        ).fetchall()
    finally:
        conn.close()
    n = len(rows)
    if n == 0:
        return empty
    agree = sum(int(r["agree"]) for r in rows)
    viol = cand_r = prod_r = gt_n = 0
    for r in rows:
        if int(r["ground_truth_known"]) and r["ground_truth_verdict"] is not None:
            gt_n += 1
            gt = str(r["ground_truth_verdict"])
            if str(r["candidate_verdict"]) != gt:
                viol += 1
            cand_r += 1 if str(r["candidate_verdict"]) == gt else 0
            prod_r += 1 if str(r["production_verdict"]) == gt else 0
    return {
        "n": n, "agreement_rate": agree / n, "fr_og_7_violations": viol,
        "cand_prod_agreement": agree / n,
        "candidate_reward": cand_r / gt_n if gt_n else 0.0,
        "production_reward": prod_r / gt_n if gt_n else 0.0,
        "n_with_ground_truth": gt_n,
    }


def write_report(
    report_path: Path, proposal: Path, soak_run_id: str, summary: dict,
) -> None:
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text("\n".join([
        f"# v10 shadow report — {soak_run_id}",
        "",
        f"- Proposal: `{proposal}`",
        f"- Soak run id: `{soak_run_id}`",
        f"- Shadow rows recorded: {summary['n']}",
        f"- Rows with ground-truth: {summary.get('n_with_ground_truth', 0)}",
        "",
        "## Summary",
        "",
        f"- Agreement rate: {summary['agreement_rate']:.4f}",
        f"- Cand↔Prod agreement (HITL proxy): "
        f"{summary['cand_prod_agreement']:.4f}",
        f"- FR-OG-7 violations: {summary['fr_og_7_violations']}",
        f"- Candidate reward (ground-truth match): {summary['candidate_reward']:.4f}",
        f"- Production reward (ground-truth match): {summary['production_reward']:.4f}",
        "",
        "_Generated by `rl.cli.shadow`. Under Amendment D v10.1-mode this is_",
        "_informational only — NOT a v10.3 writeback green-light._",
        "",
    ]), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    if not args.proposal.exists():
        print(f"[rl.shadow] proposal not found: {args.proposal}", file=sys.stderr)
        return EXIT_ERROR
    soak_run_id = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    cmd = build_soak_command(args.proposal, args.shadow_db, args.soak_args)
    if args.dry_run:
        print(" ".join(cmd))
        return EXIT_OK
    print(f"[rl.shadow] soak_run_id = {soak_run_id}")
    print(f"[rl.shadow] cmd = {' '.join(cmd)}")
    try:
        completed = subprocess.run(cmd, check=False)
    except OSError as exc:
        print(f"[rl.shadow] soak_driver spawn failed: {exc}", file=sys.stderr)
        return EXIT_ERROR
    if completed.returncode != 0:
        print(f"[rl.shadow] soak_driver exited {completed.returncode}",
              file=sys.stderr)
    summary = _summarise_shadow_db(args.shadow_db, soak_run_id)
    report_path = args.reports_dir / f"v10-shadow-{soak_run_id}.md"
    write_report(report_path, args.proposal, soak_run_id, summary)
    print(f"[rl.shadow] wrote {report_path}")
    print(json.dumps({"soak_run_id": soak_run_id, **summary}))
    return EXIT_OK


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main(sys.argv[1:]))
